### PR TITLE
Improve `pick` command to display color styles

### PR DESCRIPTION
**Pull request by hulufei**
eg. [221](https://leetcode.com/problems/maximal-square)

### CODE REVIEW

**Comment by clearloop** [comment]
Thank!! The HTML parsing process is quite complex in some way so that I didn't implement it in `leetcode-cli`, this update is not easy!

The usage of `unwrap` might be dangerous, I'll fix them to `unwrap_or()` to improve the process.

## HTML parser
I used to implement a [similar][0] HTML parser like `escaper`,  I'm considering about that if we can use [elvis][1] instead of `escaper` in the future?

## Elvis

BTW, would you like to have a look at [elvis][1] when you are free? It's an`UI Library` powered by `wasm`, faster than `vue` for 2\~3 times, `react` for 5\~8 times, it would be nice if we can develop it together one day!


[0]: https://github.com/clearloop/elvis/blob/master/src/web/tree.rs
[1]: https://github.com/clearloop/elvis

**Comment by hulufei** [comment]
It seems interesting, after a quick view at elvis, I didn't totally get it though. It's a UI Library written in rust and compiled to javascript(which is elvis.js), and then used by javascript ?

I know some rust based frontend frameworks like [Seed](https://seed-rs.org/guide/about/), what's the difference between elvis and these frameworks?

**Comment by clearloop** [comment]
`Elvis` is just better than `seed` and `yew`, don't ask me why  : -P


## Elvis

Seriously speaking, 

1. the `used by javascript` is the core design for `Elvis`, it's friendly for the frontend developers —— **they can write code like before with better performance using `Elvis`'s wasm layer**.
2. `Elvis` terms to abstract a UI structure for all platforms, you can write a rust UI once and transform them to `web`, `electron`, `flutter`, even for `Qt` in the future.

## For example

+ yew: rust the web
+ seed: rust the web, too.
+ elvis: js or rust the web as your wish, if your want to rust the mobile or desktop together, piece of a cake.

**Comment by hulufei** [comment]
That's a good marketing point:)

**Comment by clearloop** [comment]
> That's a good marketing point:)

@hulufei Hi, bro，how are you doing? There will be an activity about introducing [elvisjs][0] next Tuesday, It would be nice you join it, you can contact me at cdr.today@foxmail.com

[0]: https://github.com/elvisjs/elvis

**Pull request merged**
