### PR TITLE
change params type to `Option<Param>`

### PR DESCRIPTION
**Pull request by frrad**
Fixes https://github.com/clearloop/leetcode-cli/issues/30

### CODE REVIEW

**Comment by frrad** [comment]
I implemented your suggested fix for this too. Seems to work, I can edit 1797 with this change

**Comment by clearloop** [comment]
> I implemented your suggested fix for this too. Seems to work, I can edit 1797 with this change

After editing it, can you test && submit the problem?

**Comment by frrad** [comment]
Just checked. Those work also.

**Comment by clearloop** [comment]
Hey @frrad , thanks for your PRs!! `leetcode-cli` has just bumped to `v0.3.3` with your updates now~

**Comment by frrad** [comment]
Awesome! Thank you!

**Pull request merged**
