### PR TITLE
fix flake.nix

### PR DESCRIPTION
**Pull request by ryoppippi**
Related: #168
fixes: #166 
fixes: #169

### CODE REVIEW

**Comment by ryoppippi** [comment]
hi @clearloop !
In this PR, I changed the packaging.
Is it okay?

**Comment by ryoppippi** [comment]
I need some modification later

**Comment by clearloop** [comment]
> hi @clearloop ! In this PR, I changed the packaging. Is it okay?

yep sure! I'll help with updating it on crates.io once this PR get merged

**Comment by ryoppippi** [comment]
@clearloop 
Hi!
I modified flake.nix.

This new flake automatically reads versions from Cargo.toml, so you can manage the versions easier!

**Review by clearloop — APPROVED** [review]

**Pull request merged**
